# Missing values


```{r stations, include=FALSE}
library(tidyverse)
library(rvest)
library(robotstxt)
library(pander)
library(readxl)
#paths_allowed("https://data.ny.gov/api/views/7rrd-248n/rows.csv?accessType=DOWNLOAD&sorting=true")
stations <-read_csv("https://data.ny.gov/api/views/7rrd-248n/rows.csv?accessType=DOWNLOAD&sorting=true")
registration_url<-"https://www.nyserda.ny.gov/-/media/Files/Programs/ChargeNY/EV-Registration-Tables.xlsx"
temp <-tempfile(fileext = ".xlsx")
download.file(registration_url, destfile=temp, mode='wb')
registration_utility <- readxl::read_excel(temp, sheet =1)
registration_zipcode <- readxl::read_excel(temp, sheet =2)
registration_model <- readxl::read_excel(temp, sheet =3)
registration_country <- readxl::read_excel(temp, sheet =4)
registration_originaltime <- readxl::read_excel(temp, sheet =5)
registration_originalmake <- readxl::read_excel(temp, sheet =6)
```

<p style="font-size:23px;"> Graph missing values by variable </p>

We try using the visna graph to plot the missing values by variable, and sort by variable with the most to least missing values. 

```{r setup, include=FALSE}
 # keep this chunk in your .Rmd file
 knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```


```{r}
# need to use read.csv here to setup for visna plot.
stations <-read.csv("https://data.ny.gov/api/views/7rrd-248n/rows.csv?accessType=DOWNLOAD&sorting=true")
library(mi)
x <- missing_data.frame(stations)
library(extracat)
pander(visna(x,sort = "b"))
```

From the graph, it does not seem to have obvious patterns in the missing values. So we directly drop the columns that contains only NA values, such as Plus4 and Expected Date.


<p style="font-size:23px;"> Add another graph? </p>
