# Results
```{r stations, include=FALSE}
## COPIED: initial import of data sets

library(tidyverse)
library(rvest)
library(robotstxt)
library(pander)
library(readxl)
#paths_allowed("https://data.ny.gov/api/views/7rrd-248n/rows.csv?accessType=DOWNLOAD&sorting=true")
stations <-read_csv("https://data.ny.gov/api/views/7rrd-248n/rows.csv?accessType=DOWNLOAD&sorting=true")
registration_url<-"https://www.nyserda.ny.gov/-/media/Files/Programs/ChargeNY/EV-Registration-Tables.xlsx"
temp <-tempfile(fileext = ".xlsx")
download.file(registration_url, destfile=temp, mode='wb')
registration_utility <- readxl::read_excel(temp, sheet =1)
registration_zipcode <- readxl::read_excel(temp, sheet =2)
registration_model <- readxl::read_excel(temp, sheet =3)
registration_country <- readxl::read_excel(temp, sheet =4)
registration_originaltime <- readxl::read_excel(temp, sheet =5)
registration_originalmake <- readxl::read_excel(temp, sheet =6)


## drop 3 columns with only NA values, will drop more irrelevant columns.

stations <- stations %>%
      select(- c("Plus4", "Expected Date", "EV Other Info"))

```



```{r}
pander(head(stations))
# TODO: transfer data types for plotting and write up to 03.rmd
```



