--- 
title: "Analysis on EV Charging Station in NY State"
author: "Dingwen Xie, Yuanhang Chen, Yu Liu"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

The electric car has been developed rapidly over the past ten years, accounting for 2.6% of global car sales and about 1% of global car stock in 2019, registered an approximate 40% year-on-year increase. In International Energy Agencies (IEA) Global EV Outlook 2020( https://www.iea.org/reports/global-ev-outlook-2020), it claims that by 2040, over half of all passenger vehicles sold will be electric, which means that electric vehicles will be the general trend, and this field will become hot in the next 30 years. We are looking forward to the bloom of electric vehicles, but are skeptical about the claim either. After all, electric vehicles only accounted for 2.6% of global car sales in 2019. This claim aroused our enthusiasm in this field. So, we decided to set the theme of this project as electric vehicles. The part closely related to the future of electric vehicles is the popularity and distribution of its charging stations. The United States takes the second largest market share in private electric vehicles chargers. As students of Columbia University, New York City is where we are most concerned about. Therefore, we finally decided to focus our project on the distribution of electric vehicles charging stations in New York, hoping to get a glimpse of the future development of this field through this project. In this project, we will focus on three major questions: 
1.the change of the number of EV charging stations and EV registration over time.
2.Geological distribution of charging stations in NY state.
3.Analysis of the data set on specific categories such as EV connector types and models.


Related datasets are downloaded from this website (https://www.nyserda.ny.gov/All-Programs/Programs/ChargeNY/Support-Electric/Data-on-Electric-Vehicles-and-Charging-Stations). We will use the EV registration map and EV charging station map. 
